apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: demo
  name: demo
  namespace: default
spec:
  ports:
    - name: "30000"
      port: 30000
      targetPort: 30000
  selector:
    io.kompose.service: demo
status:
  loadBalancer: {}
