apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: demo
  name: demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: demo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/playground-default: "true"
        io.kompose.service: demo
    spec:
      containers:
        - args:
            - flagd
          env:
            - name: FIB_SERVICE_URL
              value: http://fib-service:30001
            - name: FLAGD_HOST
              value: flagd
            - name: GO_FEATURE_FLAG_URL
              value: http://go-feature-flag:1031
            - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
              value: jaeger
            - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
              value: "6832"
          image: ghcr.io/open-feature/playground-app:v0.11.0
          name: demo
          ports:
            - containerPort: 30000
              hostPort: 30000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /opt/playground/config/flagd/flags.json
              name: demo-claim0
      restartPolicy: Always
      volumes:
        - name: demo-claim0
          persistentVolumeClaim:
            claimName: demo-claim0
status: {}
