apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: go-feature-flag
  name: go-feature-flag
  namespace: default
spec:
  ports:
    - name: "1031"
      port: 1031
      targetPort: 1031
  selector:
    io.kompose.service: go-feature-flag
status:
  loadBalancer: {}
