apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
  namespace: openfeature
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "6832"
      port: 6832
      protocol: UDP
      targetPort: 6832
  selector:
    io.kompose.service: jaeger
status:
  loadBalancer: {}

apiVersion: v1
kind: Service
metadata:
  name: jaeger-external
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: jaeger
  ports:
  - name: http
    port: 16686
    targetPort: 16686